###
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "name": "aaa",
  "surname": "aaa",
  "email": "aaa@wasdorld.com",
  "password": "aaaaaa"
}

###
POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
  "email": "aaa@wasdorld.com",
  "password": "aaaaaa"
}

###
POST http://localhost:3001/api/auth/refresh
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImRlOWVkOGVjLWFiYzUtMTFlYy1hMTFhLWVmNTZkZjVlMzZmNSIsIm5hbWUiOiJhYWEiLCJzdXJuYW1lIjoiYWFhIiwiZW1haWwiOiJhYWFAd2FzZG9ybGQuY29tIiwiY3JlYXRlRGF0ZSI6IjIwMjItMDMtMjRUMjI6NTc6NTUuMDAwWiIsIm1vZGlmeURhdGUiOiIyMDIyLTAzLTI0VDIyOjU3OjU1LjAwMFoiLCJyb2xlIjoidXNlciIsInBob25lIjpudWxsLCJpYXQiOjE2NDgxNjMwNzAsImV4cCI6MTY0ODE3MDI3MH0.3k7H6VcbPqpUDzYgAgy24nZa-jcNIS2KcJatyLRPW6A"
}

###
GET http://localhost:3001/api/users/details
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjMwNDgxZDUzLTkwMjktMTFlYy05NzFhLThhZmM1M2FhNTliZCIsIm5hbWUiOiJ6Iiwic3VybmFtZSI6IndvcmxkIiwiZW1haWwiOiJoZWxsb0B3YXNkb3JsZC5jb20iLCJjcmVhdGVEYXRlIjoiMjAyMi0wMi0xN1QxOTozODoyMS4wMDBaIiwibW9kaWZ5RGF0ZSI6IjIwMjItMDMtMjJUMjA6MjI6MjIuMDAwWiIsInJvbGUiOiJhZG1pbiIsInBob25lIjpudWxsLCJpYXQiOjE2NDc5ODM1MzgsImV4cCI6MTY0Nzk4OTUzOH0.-nVhLi9lQ90bqCA08Eb_pE1SIVqyYwcazlSUJhG5gOc

###
POST http://localhost:3001/api/reservation
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjMwNDgxZDUzLTkwMjktMTFlYy05NzFhLThhZmM1M2FhNTliZCIsIm5hbWUiOiJ6Iiwic3VybmFtZSI6IndvcmxkIiwiZW1haWwiOiJoZWxsb0B3YXNkb3JsZC5jb20iLCJjcmVhdGVEYXRlIjoiMjAyMi0wMi0xN1QxOTozODoyMS4wMDBaIiwibW9kaWZ5RGF0ZSI6IjIwMjItMDItMTdUMTk6Mzg6MjEuMDAwWiIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjQ3ODE5NTk1LCJleHAiOjE2NDc4MjA0OTV9.-kCWTVszgKfQuHd065fs-t4fdiFopZhi5_CIoivqwzQ
Content-Type: application/json

{
  "reservationId": "17"
}

###
DELETE http://localhost:3001/api/auth/logout
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImRlOWVkOGVjLWFiYzUtMTFlYy1hMTFhLWVmNTZkZjVlMzZmNSIsIm5hbWUiOiJhYWEiLCJzdXJuYW1lIjoiYWFhIiwiZW1haWwiOiJhYWFAd2FzZG9ybGQuY29tIiwiY3JlYXRlRGF0ZSI6IjIwMjItMDMtMjRUMjI6NTc6NTUuMDAwWiIsIm1vZGlmeURhdGUiOiIyMDIyLTAzLTI0VDIyOjU3OjU1LjAwMFoiLCJyb2xlIjoidXNlciIsInBob25lIjpudWxsLCJpYXQiOjE2NDgxNjI2ODYsImV4cCI6MTY0ODE2OTg4Nn0.rHJnE7rk6EdFZGMrH2k-jnbLYjUcqliTemmR5LdMCwM"
}

###
POST http://localhost:3001/api/timetable
Content-Type: application/json

{
  "email": "hello@wasdorld.com",
}

###
GET http://localhost:3001/api/reservations/daily/1653771600000
Content-Type: application/json

